# Generated by Django 4.2.9 on 2024-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_userstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('caloric', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carboon', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DirectoryFood',
            },
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='callories_received',
        ),
    ]
