# Generated by Django 4.2.9 on 2024-02-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_directoryfood_user_create_alter_userstat_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directoryfood',
            old_name='carboon',
            new_name='carbon',
        ),
    ]
