# Generated by Django 4.2.9 on 2024-02-06 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_rename_carboon_directoryfood_carbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('caloric', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carbon', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('user_create', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
