# Generated by Django 4.2.9 on 2024-02-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_directoryingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.directoryfood')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.directoryingredients')),
            ],
        ),
    ]
