# Generated by Django 4.2.9 on 2024-02-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_recipefood_gram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directoryingredients',
            options={'verbose_name_plural': 'DirectoryIngredients'},
        ),
        migrations.AlterModelOptions(
            name='recipefood',
            options={'verbose_name_plural': 'RecipeFood'},
        ),
    ]
