# Generated by Django 4.2.9 on 2024-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_alter_directoryingredients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='carbon_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='fat_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstat',
            name='protein_burned',
            field=models.IntegerField(default=0),
        ),
    ]
