# Generated by Django 4.2.9 on 2024-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_userstat_carbon_burned_userstat_fat_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryfood',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
