# Generated by Django 4.2.9 on 2024-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_directoryfood_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='recommended_calories',
            field=models.IntegerField(null=True),
        ),
    ]
